### PR TITLE
Enable NaN tests

### PR DESCRIPTION
**Pull request by fpetkovski**
This commit enables NaN tests by using the latest version of efficientgo/core.

### CODE REVIEW

**Review by saswatamcode — APPROVED** [review]
LGTM! 

But maybe we can split the NaN test cases into a separate testing function that uses the go-cmp option?

Also the test seems to timeout after 1m in CI

**Comment by fpetkovski** [comment]
What would be the advantage of splitting the tests? Don't we always want to treat NaNs as equal?

**Comment by saswatamcode** [comment]
The advantage I was thinking of was that we'd be aware that those cases return NaN and aren't comparing any numerical data. If not separate test function, then maybe just comments to highlight which test case returns NaN? 🙂 
I don't feel too strongly about this, so not a blocker!

**Comment by fpetkovski** [comment]
Hm, so with native histograms we will have cases where we return a mix of NaNs and real data, so the result won't always be binary. Maybe we can detect in the test case whether there are NaNs and print this out? I would like to avoid another test function where we have to repeat things. Even the separation between range and instant queries is getting a bit hard to manage.

**Comment by saswatamcode** [comment]
I think detecting and printing might be best!

**Comment by fpetkovski** [comment]
Updated 👍

**Review by saswatamcode — APPROVED** [review]
Thanks! LGTM!

**Comment by yeya24** [comment]
Just curious, I am seeing some NaN related errors in my tests. The old engine result has NaN while the new engine doesn't. Is this a bug of the new engine or a flaw of the NaN comparison code?

```
vector(--scalar(atan(irate({__name__="http_requests_total"}[1m] offset 4m21s))))
    engine_test.go:81: Applying comparison with NaN equality.
    testutil.go:91: engine_test.go:82: ""
        
        	exp: &promql.Result{Err:error(nil), Value:promql.Vector{promql.Sample{Point:promql.Point{T:1677955629940, V:NaN, H:(*histogram.FloatHistogram)(nil)}, Metric:labels.Labels{}}}, Warnings:storage.Warnings(nil)}
        
        	got: &promql.Result{Err:error(nil), Value:promql.Vector{}, Warnings:storage.Warnings(nil)}
```

**Comment by fpetkovski** [comment]
Yes, this is a bug probably in atan function but worth double checking. We can haven an issue to investigate.

**Pull request merged**
