### PR TITLE
add support for a few functions

### PR DESCRIPTION
**Pull request by kama910**
Signed-off-by: Kama Huang <kamatogo13@gmail.com>
Support date/time related functions.

### CODE REVIEW

**Comment by fpetkovski** [comment]
This originates here: https://github.com/thanos-community/promql-engine/blob/3e3e0b3c510bae274b2af7bcf74eea40282c0425/execution/execution.go#L114-L116

I think you could even remove that check and see what happens.

**Comment by yeya24** [comment]
@fpetkovski I see those functions are Variadic functions indeed. Shall we support Variadic function in our framework first and then tackle those promql functions?

**Comment by fpetkovski** [comment]
I was hoping that we already support this because the function operator can take an arbitrary number of input operators. But I am not 100% sure if this would cover variadic functions.

**Review by yeya24 — APPROVED** [review]
Thanks for your contribution!

**Review by GiedriusS — APPROVED** [review]

**Pull request merged**
