### PR TITLE
fix data race

### PR DESCRIPTION
**Pull request by liguozhong**
fix data race.

fix : https://github.com/thanos-community/promql-engine/issues/249
image

### CODE REVIEW

**Comment by liguozhong** [comment]
copy array beforo slice append ,avoid array behind slice datarace.
image

image

**Review by fpetkovski — COMMENTED** [review]
Thanks for the PR, but to me looks like a usage problem. The test is trying to modify input parameters while the engine is being instantiated.

**Comment by liguozhong** [comment]
hi,  thanks for your review tips. I checked the test code of cortex again.
this is cortex test code about thanos/promql-engine, The test do not try to modify input parameters.
`								LogicalOptimizers: logicalplan.AllOptimizers,
`
```go
func TestChunkQueryable(t *testing.T) {
	t.Parallel()

	opts := promql.EngineOpts{
		Logger:             log.NewNopLogger(),
		ActiveQueryTracker: promql.NewActiveQueryTracker(t.TempDir(), 10, log.NewNopLogger()),
		MaxSamples:         1e6,
		Timeout:            1 * time.Minute,
	}
	for _, thanosEngine := range []bool{false, true} {
		for _, testcase := range testcases {
			for _, encoding := range encodings {
				for _, query := range queries {
					t.Run(fmt.Sprintf("%s/%s/%s/ thanos engine enabled = %t", testcase.name, encoding.name, query.query, thanosEngine), func(t *testing.T) {
						//parallel testing causes data race
						var queryEngine v1.QueryEngine
						if thanosEngine {
							queryEngine = engine.New(engine.Opts{
								EngineOpts:        opts,
								LogicalOptimizers: logicalplan.AllOptimizers,
							})
						} else {
							queryEngine = promql.NewEngine(opts)
						}

						store, from := makeMockChunkStore(t, 24, encoding.e)
						queryable := newMockStoreQueryable(store, testcase.f)
						testRangeQuery(t, queryable, queryEngine, from, query)
					})
				}
			}
		}
	}
}
```
The modification of this slice occurs in this function in thanos/promql-engine.
image

**Review by fpetkovski — APPROVED** [review]
Leaving for @yeya24 to take a look.

**Review by yeya24 — APPROVED** [review]
Thanks

**Pull request merged**
